## YAML Template.
fichefrais :
    type: rest
    resource:     "FraisApiBundle:FichefraisRest"
    name_prefix:  api_fichefrais_

etat :
    type: rest
    resource:     "FraisApiBundle:EtatRest"
    name_prefix:  api_etat_
  
fichehorsforfait :
    type: rest
    resources:    "FraisApiBundle:FichehorsforfaitRest"
    name_prefix:  api_fraishorsforfait_

fraisforfait :
    type: rest
    resources:   "FraisApiBundle:FicheforfaitRest"
    name_prefix: api_fraisforfait_

typefrasiforfait :
    type: rest
    resources:  "FraisApiBundle:TypefraisforfaitRest"
    name_prefix: api_typefraisforfait_

